=== VladimirMar/teg_financ/importXML/marca-modelo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="marca-modelo" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="marca-modelo">
<xsd:annotation>
<xsd:appinfo/>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="marca_modelo" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== VladimirMar/teg_financ/importXML/marca-modelo.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="marca-modelo.xsd" generated="2026-04-09T08:14:14">
<marca-modelo/>
<marca-modelo>
<marca_modelo>AGRALE/8.5NEOBUS THUNDER</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>AGRALE/BUSSCAR MICRUSS O</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>AGRALE/MASCA  GRANMICRO O</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>AGRALE/MASCA GRMICRO E O</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>AGRALE/MAXIBUS ASTOR</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>AGRALE/MPOLO SEN MIDI ON</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>AGRALE/NEOBUS THUNDER</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>CITROEN/JUMP GREENCAR ES</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>CITROEN/JUMPER</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>CITROEN/JUMPER CLASSYVAN</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>CITROEN/JUMPER EUROLAF P</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>CITROEN/JUMPER GREENCAR ES</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>CITROEN/JUMPER JAEDI MIC</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>CITROEN/JUMPER M33M 2.3</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>CITROEN/JUMPER M33M 23S</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>CITROEN/JUMPER M33M HDI</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>CITROEN/JUMPER M35L HDI</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>CITROEN/JUMPER M35LH 2.3</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>CITROEN/JUMPER MBS 33M16</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>CITROEN/JUMPER REVES ESC</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>CITROEN/JUMPER TRA 35ESC</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/ DUCA ESCOLAR FFBM25</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUC M APLIKART M20</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUC TRANSFORMERS TE</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCA ESCOLAR FFBM2</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCA ESCOLAR FFBM25</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCA ESCOLAR FFBM26</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCA15 FFORMA MIC20</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCACOMFFORMA MIC21</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCAMA FFORMA MIC23</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCATO 15REFAMMIC13</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCATO C REFAMMIC12</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCATO COMBINATO</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCATO ESCOLAR FFBM25</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCATO FABUSFORMA</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCATO GCASA MIC1</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCATO GREENCAR MO1</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCATO GUERRA MC 16</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCATO GUERRA MC 20</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCATO M BUS RONTAN</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCATO M EMBRAFI 16</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCATO M JAEDI OESC</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCATO M REFAMMIC11</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCATO MARTICAR 16</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCATO MARTICAR 17</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCATO MAXI JAEDI T</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCATO MC TCA MIC</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCATO MINIBUS</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCATO MINIBUS T</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCATO MINIBUSQ</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCATO MODIFICAR TP</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCATO MU CIRILO A3</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCATO MUL ATENA MI</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCATO MUL REVESCAP</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCATO MULT JAEDI T</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCATO MULT TAKO MI</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCATO MULTI</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCATO MULTI REVESC</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCATO NIKS</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCATO NIKS 16</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCATO NIKS MIC 20</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCATO NIKS MULT 16</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCATO REVESCAP</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCATO TRANSFORM P</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCATO VIPK</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/DUCTAO MINIBUS</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>FIAT/FIAT</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/FIAT DUCATO ENGESIGEXE</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/FIAT DUCATO ENGESIGMIC</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/FIAT DUCATO FFORMA ESC</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/FIAT DUCATO FFORMA M09</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/FIAT DUCATO GREENCACES</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/FIAT DUCATO M NIKS PAS</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/FIAT DUCATO TRANSF MP</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/FORD TRANSIT 350L BUS</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/FORD TRANSIT 410 B</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/FORD TRANSIT 460 B</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/FORD TRANSIT 460 B AT</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/FORD TRANSIT FFORMA ES</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/FORD TRANSIT GUERRA E</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/FORD TRANSIT NIKS MO17</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/FORD TRANSIT REVES 16L</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/FORD TRANSIT VIPK PAS</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/FORD TRST MODIFICAR TP</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/HYUNDAI H100 GLS</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/JINBEI FABUSFORMA M35</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/JINBEI TOPIC L</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/JINBEI TOPIC SL</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/KIA BESTA GS GRAND2</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/M BENZ 415 NIKS PAS</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/M. BENZ SPRINTER FFB ES</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/M. BENZ311CDI  SPRINTERM</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/M. BENZ313CDI SPRINTERM</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/M.BENZ 311 CDI FFBM 27</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/M.BENZ 311 NIKS PAS</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/M.BENZ 313 CDI FFBM 28</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/M.BENZ 415 GUERRA MC20</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/M.BENZ 415 TRANSF PAS</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/M.BENZ 415CDI VIPK ACE</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/M.BENZ 415CDISPRINTERM</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/M.BENZ 415DISPRINTERM</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/M.BENZ 415SPRINTE VIPK</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/M.BENZ 416 FFORMA P</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/M.BENZ 416 GUERRA ESC</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/M.BENZ 416 NIKS ESC</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/M.BENZ 416 VIPK ESC</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/M.BENZ 416CDI VIPK M20</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/M.BENZ 416CDISPRINTERM</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/M.BENZ 417 GUERRA 16P</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/M.BENZ 417 GUERRA ESC</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/M.BENZ 417 SPRINTER M</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/M.BENZ 417 TAKO PAS</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/M.BENZ 515CDISPRINTERM</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/M.BENZ 517 GUERRA ESC</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/M.BENZ CDI SPR TCA MIC</marca_modelo>
</marca-modelo>
<marca-modelo>
<marca_modelo>I/M.BENZ COMIL BELLA O</marca_modelo>
</marca-modelo>
<marca-modelo>
