=== VladimirMar/teg_financ/importXML/Seguradoras.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Seguradoras" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Seguradoras">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="Código" index-key="Código " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="Controle " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAADGHsu6gbZzRa4GwmBuxfFBAAAAAGAWnpDMzuVAbwBmAHQAIABTAGUA
ZwB1AHIAYQBkAG8AcgBhAHMAAAAAAAAAwfGHix8k/EaAp3oSx/i9KQcAAADGHsu6
gbZzRa4GwmBuxfFBQwDzAGQAaQBnAG8AAAAAAAAAi7hpcvwO3ESqb2ul7qt9ygcA
AADGHsu6gbZzRa4GwmBuxfFBQwBvAG4AdAByAG8AbABlAAAAAAAAAF1cdHyeRGZE
vmqq4hDOsJ8HAAAAxh7LuoG2c0WuBsJgbsXxQUwAaQBzAHQAYQAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAADAAAAAQAAAAAAAAAAAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="GUID" type="9" value="xh7LuoG2c0WuBsJgbsXxQQ==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="Código" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="GUID" type="9" value="wfGHix8k/EaAp3oSx/i9KQ==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Controle" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="GUID" type="9" value="i7hpcvwO3ESqb2ul7qt9yg==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Lista" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="3840"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="GUID" type="9" value="XVx0fJ5EZkS+aqriEM6wnw==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== VladimirMar/teg_financ/importXML/Seguradoras.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Seguradoras.xsd" generated="2026-04-08T12:58:40">
<Seguradoras>
<Código>2</Código>
<Controle>1</Controle>
<Lista>PORTO SEGURO</Lista>
</Seguradoras>
<Seguradoras>
<Código>3</Código>
<Controle>2</Controle>
<Lista>INVESTPREV</Lista>
</Seguradoras>
<Seguradoras>
<Código>4</Código>
<Controle>3</Controle>
<Lista>AZUL SEGUROS</Lista>
</Seguradoras>
<Seguradoras>
<Código>5</Código>
<Controle>4</Controle>
<Lista>BB SEGUROS</Lista>
</Seguradoras>
<Seguradoras>
<Código>6</Código>
<Controle>5</Controle>
<Lista>LIBERTY SEGUROS</Lista>
</Seguradoras>
<Seguradoras>
<Código>7</Código>
<Controle>6</Controle>
<Lista>MAPFRE</Lista>
</Seguradoras>
<Seguradoras>
<Código>8</Código>
<Controle>7</Controle>
<Lista>ZURICH</Lista>
</Seguradoras>
<Seguradoras>
<Código>9</Código>
<Controle>8</Controle>
<Lista>ITAÚ</Lista>
</Seguradoras>
<Seguradoras>
<Código>10</Código>
<Controle>9</Controle>
<Lista>HDI SEGUROS</Lista>
</Seguradoras>
<Seguradoras>
<Código>11</Código>
<Controle>10</Controle>
<Lista>NOBRE SEGUROS</Lista>
</Seguradoras>
<Seguradoras>
<Código>12</Código>
<Controle>11</Controle>
<Lista>TOKIO MARINE</Lista>
</Seguradoras>
<Seguradoras>
<Código>13</Código>
<Controle>12</Controle>
<Lista>ESSOR SEGUROS</Lista>
</Seguradoras>
<Seguradoras>
<Código>14</Código>
<Controle>13</Controle>
<Lista>SOMPO SEGUROS</Lista>
</Seguradoras>
<Seguradoras>
<Código>15</Código>
<Controle>14</Controle>
<Lista>SULAMERICA</Lista>
</Seguradoras>
<Seguradoras>
<Código>16</Código>
<Controle>15</Controle>
<Lista>PREFERENCIAL CIA DE SEGUROS</Lista>
</Seguradoras>
<Seguradoras>
<Código>17</Código>
<Controle>16</Controle>
<Lista>ALLSEG SEGURADORA</Lista>
</Seguradoras>
<Seguradoras>
<Código>18</Código>
<Controle>17</Controle>
<Lista>KOVR SEGURADORA</Lista>
</Seguradoras>
<Seguradoras>
<Código>19</Código>
<Controle>18</Controle>
<Lista>EZZE SEGUROS</Lista>
</Seguradoras>
<Seguradoras>
<Código>20</Código>
<Controle>19</Controle>
<Lista>SUHAI</Lista>
</Seguradoras>
<Seguradoras>
<Código>21</Código>
<Controle>20</Controle>
<Lista>SOMBRERO</Lista>
</Seguradoras>
<Seguradoras>
<Código>22</Código>
<Controle>21</Controle>
<Lista>ALLIANZ</Lista>
</Seguradoras>
</dataroot>
